#!/usr/bin/env zsh

zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' group-name ''
zstyle ':completion:*:descriptions' format '%B%F{yellow}--- %d ---%f%b'
zstyle ':completion:*:messages' format '%B%F{red}%d%f%b'
zstyle ':completion:*:warnings' format '%B%F{red}No matches for: %d%f%b'
zstyle ':completion:*' verbose true
zstyle ':completion:*:options' description yes
zstyle ':completion:*:processes' command 'ps -u $USER -o pid,stat,%cpu,%mem,command -w'
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:git-*:*' tag-order 'heads'
zstyle ':completion:*:cd:*' tag-order local-directories directory-stack path-directories
zstyle ':completion:*:cd:*' ignore-parents parent pwd
zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin
zstyle ':completion:*' matcher-list '' 'm:{a-z-_}={A-Z_-}' 'r:|[._-]=* r:|=* l:|=*'