#!/bin/bash

current_branch=`git rev-parse --abbrev-ref HEAD`
current_version=`cat $HOME/dotfiles/VERSION 2>/dev/null`
remote_version=`curl -s https://raw.githubusercontent.com/kawaken/dotfiles/$current_branch/VERSION`

function err_msg() {
  echo "dotfiles version is different from remote."
  echo "=========================================="
  echo "current_branch   : $current_branch"
  echo "current_version  : $current_version"
  echo "remote_version   : $remote_version"
}

if [ "$current_version" != "$remote_version" ]; then
  [[ "$1" = '-v' ]] && err_msg
  exit 1
fi

