#!/bin/bash

name=$(git config --get user.name)
email=$(git config --get user.email)

if [ $# -lt 1 ]; then
  echo "user.name: $name"
  echo "user.email: $email"
  exit
fi

function usage() {
  echo "Usage:"
  echo "     set user.name and user.email interactively"
  echo "     git user --set"
}

function set_user() {
  echo -n "Your name: "; read name_
  echo -n "Your email: "; read email_

  if [ -n "$name_" ]; then
    git config --file $HOME/.gitconfig.local user.name "$name_"
  fi
  if [ -n "$email_" ]; then
    git config --file $HOME/.gitconfig.local user.email "$email_"
  fi
}

case $1 in
  --set) set_user;;
  *) usage;;
esac
