#!/bin/bash

function linkage() {
  for f in `ls $1/_*`; do
    ln -sf $f `basename $f | tr '_' '.'`
  done
}

cd $HOME
linkage dotfiles/vim
linkage dotfiles/git
linkage dotfiles/zsh

mkdir -p $HOME/bin

ln -sf $HOME/dotfiles/scripts/git-user $HOME/bin/git-user
ln -sf $HOME/dotfiles/git/hooks $HOME/.git-hooks
