#!/bin/bash

mkdir -p ~/.vim/{tmp,after}

# install vim-unbundle
if [ ! -d ~/.vim/vim-unbundle ]; then
  echo "clone: vim-unbundle"
  git clone -q https://github.com/sunaku/vim-unbundle.git ~/.vim/vim-unbundle
fi

bundles=(
  'altercation/vim-colors-solarized.git'

  'Shougo/vimproc.vim'
  'vim-scripts/QuickBuf.git'
  'thinca/vim-quickrun'
  'scrooloose/nerdtree'
  'ctrlpvim/ctrlp.vim'
  'scrooloose/syntastic'
  'milkypostman/vim-togglelist'
  'Shougo/neocomplete.vim'

  'google/vim-ft-go'
  'vim-jp/vim-go-extra'
)

mkdir -p $HOME/.vim/bundle

cd $HOME/.vim/bundle
for repo in ${bundles[@]}; do
  if [ ! -d `basename $repo .git` ]; then
    echo "clone: $repo"
    git clone -q "https://github.com/${repo}"
  fi
done

ln -n -sf ~/dotfiles/vim_ftplugin ~/.vim/after/ftplugin

# make vimproc
if [ -d vimproc.vim ]; then
  (cd vimproc.vim; make)
fi
