#!/bin/bash

cd $HOME
for f in `ls $HOME/dotfiles/_*`; do
  ln -sf $f `basename $f | tr '_' '.'`
done

for gf in `ls $HOME/dotfiles/git/_*`; do
  ln -sf $gf `basename $gf | tr '_' '.'`
done

mkdir -p $HOME/bin

ln -sf $HOME/dotfiles/scripts/git-user $HOME/bin/git-user
ln -sf $HOME/dotfiles/git/hooks $HOME/.git-hooks
