#!/bin/bash -e

# functions
function main_loop() {
    func="$1"; shift

    cd `git rev-parse --show-toplevel`
    if [ $# -gt 0 ]; then
        files=$@
    else
        files=`find -mindepth 1 -maxdepth 1 -type f -name '_*' -printf '%P\n'`
    fi
    for underfile in ${files[@]}; do
        dotfile=`echo $underfile | sed -e s/_/./`
        $func
    done
}

function init() {
  if ( git --version | grep -q -v -Ee " (1\.[89])|(2\.0)" ); then
    echo "git version is required over 1.8"
    git --version
    return 1
  fi

  # install prezto
  zsh -c 'git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"'

  # make projects dir
  mkdir -p ~/projects
}

function create_link() {
  echo "ln -sf $underfile $HOME/$dotfile"
  ln -sf $HOME/dotfiles/$underfile $HOME/$dotfile
}


cd $HOME
if [ ! -d $HOME/dotfiles ]; then
  git clone https://github.com/kawaken/dotfiles.git
fi

cd dotfiles

init
main_loop create_link
