#!/bin/bash

bundles=(
  'sunaku/vim-unbundle.git'
  'altercation/vim-colors-solarized.git'
  'Shougo/neocomplete.git'
  'thinca/vim-quickrun'
  'vim-scripts/QuickBuf.git'
  'vim-scripts/matchit.zip.git'
  'scrooloose/nerdtree'
  'google/vim-ft-go'
  'vim-jp/vim-go-extra'
  'majutsushi/tagbar'
)

mkdir -p $HOME/.vim/bundle

cd $HOME/.vim/bundle
for repo in ${bundles[@]}; do
  if [ ! -d `basename $repo .git` ]; then
    echo "clone: $repo"
    git clone -q "https://github.com/${repo}"
  fi
done
