#!/bin/bash

# install vim-unbundle
mkdir -p ~/.vim/tmp

if [ ! -d ~/.vim/vim-unbundle ]; then
  echo "clone: vim-unbundle"
  git clone -q https://github.com/sunaku/vim-unbundle.git ~/.vim/vim-unbundle
fi

bundles=(
  'altercation/vim-colors-solarized.git'

  'vim-scripts/QuickBuf.git'
  'thinca/vim-quickrun'
  'scrooloose/nerdtree'
)

mkdir -p $HOME/.vim/bundle

cd $HOME/.vim/bundle
for repo in ${bundles[@]}; do
  if [ ! -d `basename $repo .git` ]; then
    echo "clone: $repo"
    git clone -q "https://github.com/${repo}"
  fi
done
