#!/usr/bin/env zsh

set -euo pipefail

# JIRA関数が定義されていない場合のみsource
[[ -z ${functions[jira_fetch]} ]] && source ~/dotfiles/zsh/plugins/jira

cleanup() {
    exit 0
}

trap cleanup SIGTERM SIGINT

while true; do
    # jira_fetch関数を使用してデータ更新
    jira_fetch
    sleep 300
done